name: Reusable .NET Build & Deploy

on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
      project_path:
        required: true
        type: string
      publish_branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ${{ inputs.project_path }}

      - name: Build
        run: dotnet build ${{ inputs.project_path }} --configuration Release --no-restore

      - name: Run Tests and Collect Coverage
        run: |
          echo "Searching for test projects..."
          TEST_PROJECTS=$(find . -type f -name "*Tests.csproj")

          if [ -z "$TEST_PROJECTS" ]; then
            echo "No test projects found."
            exit 1
          fi

          echo "Found test projects:"
          echo "$TEST_PROJECTS"

          for proj in $TEST_PROJECTS; do
            echo "Running tests for: $proj with coverage"
            dotnet test "$proj" --configuration Release --collect:"XPlat Code Coverage" --verbosity normal
          done

      - name: Generate Coverage Report
        run: |
          echo "Finding coverage files..."
          COVERAGE_FILES=$(find . -type f -path "*/TestResults/*/coverage.cobertura.xml")
              
          if [ -z "$COVERAGE_FILES" ]; then
            echo "No coverage files found."
            exit 1
          fi
              
          echo "Found coverage files:"
          echo "$COVERAGE_FILES"
              
          # Install reportgenerator
          dotnet tool install -g dotnet-reportgenerator-globaltool
              
          # Generate HTML report and TextSummary
          reportgenerator -reports:"$COVERAGE_FILES" -targetdir:coverage-report -reporttypes:"HtmlInline_AzurePipelines;TextSummary"

      # Publish artifact only on the publish branch
      - name: Publish Artifact
        if: github.ref == format('refs/heads/{0}', inputs.publish_branch)
        run: dotnet publish ${{ inputs.project_path }} -c Release -o published

      - name: Upload Artifact
        if: github.ref == format('refs/heads/{0}', inputs.publish_branch)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.project_name }}
          path: published/

      - name: Upload Code Coverage Artifact
        if: github.ref == format('refs/heads/{0}', inputs.publish_branch)
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage-report/
